name = "ruhal/cip113"
version = "0.0.0"
compiler = "v1.1.19"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'ruhal/cip113'"

[repository]
user = "ruhal"
project = "cip113"
platform = "github"

[[dependencies]]
name = "aiken-lang/merkle-patricia-forestry"
version = "2.0.0"
source = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2"
source = "github"

[config]
